# Generated by Django 3.1.2 on 2020-10-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20201002_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['curso', 'nome', '-matricula'], 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rg',
        ),
    ]
