# Generated by Django 3.1.2 on 2020-12-13 21:31

import django.contrib.auth.models
from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20201125_1809'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('coordenadores', usuario.models.CoordenadorAtivoManager()),
                ('orientadores', usuario.models.OrientadorAtivoManager()),
                ('professores', usuario.models.ProfessorAtivoManager()),
                ('alunos', usuario.models.AlunoAtivoManager()),
                ('secretarias', usuario.models.SecretariaAtivoManager()),
                ('convidados', usuario.models.ConvidadoAtivoManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='fone',
            field=models.CharField(default='55999999999', help_text='ATENÇÃO: Somente os NÚMEROS', max_length=14, verbose_name='Celular par contato *'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('COORDENADOR', 'Coordenador'), ('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno'), ('SECRETÁRIA', 'Secretária'), ('AVALIADOR CONVIDADO', 'Avaliador Convidado')], default='ALUNO', help_text='* Campos obrigatórios', max_length=19, verbose_name='Tipo do usuário *'),
        ),
    ]
